### PR TITLE
Perf improvements for agon-flash

### PR DESCRIPTION
**Pull request by leighbb**
Hi, if you are making lots of updates, it's handy to be able to re-flash quickly.

This pull request:
1) introduces an assembler crc32() adapted for eZ80 from https://github.com/maxim-zhao/z80-crc32/
2) uses mos_fread() instead of mos_fgetc()

Speeds up loading file and checking crc32 from about 14 seconds to 0.5 seconds on my Agon Light 2.

Happy for any feedback you may have.

Cheers,

Leigh.

Before:
https://github.com/envenomator/agon-flash/assets/5477785/a2e63456-32d4-45cb-97e8-0b8978f076cc

After:
https://github.com/envenomator/agon-flash/assets/5477785/67347d7a-0e52-41c0-b38a-49e7426cda77

### CODE REVIEW

**Comment by envenomator** [comment]
Hi Leigh,

Thanks for these performance updates, in particular the crc32. Because the tool couldn't make assumptions as to the presence of mos_fread (which was only introduced in 1.03), I specifically chose to just use mos_fgetc. 
Using mos_fread, we'd need to make another version for 1.03 onwards, which I feel will be hard for most users selecting the right version.

**Comment by envenomator** [comment]
Also, apart from fingerprinting code in flash, there is no standard way to identify which MOS version is running currently

**Comment by envenomator** [comment]
Quick question; why introduce the ‘TEXT’ section and not use an aligned DATA segment?

**Comment by leighbb** [comment]
Thanks for the feedback. Perhaps an enhancement request for a mos_version call (obviously won't help right now but will down the line).  I don't even know why I used TEXT although it does make the program a few bytes shorter.
I will update the pull request accordingly, once I figure out how.

**Comment by leighbb** [comment]
I've pushed the revert of the mos_fread and changing from TEXT to DATA. Hopefully that is visible (I'm not very familiar with github),

**Comment by envenomator** [comment]
After some consideration and testing, I've also pulled in your changes using mos_fread, and heavily redacted the README for users to follow. Just released v1.3 with your additions. Thanks!

**Pull request merged**
